# https://pages.github.com/themes/
# theme: minima
theme: jekyll-theme-midnight

title: Patjlm's blog on Rayn
author: Patrick Martin
description: Description of the wonderful services provided by Rayn https://rayn.money
