# https://pages.github.com/themes/
# theme: minima
theme: jekyll-theme-midnight

title: A description of Rayn
author: Patrick Martin
description: Description of the wonderful services provided by Rayn - a modern neo-bank focused on earnings
