# https://pages.github.com/themes/
# theme: minima
theme: jekyll-theme-midnight

title: Patjlm's blog on Rayn
author: Patrick Martin
description: Description of the wonderful services provided by [Rayn](https://rayn.money). Use my [referral link](https://rayn.money/app-referral/?referral=043144a6a9a9310624951513b931b6d73e9a49353d1969669507bee7ccbe4727)!
